// Generated by gencpp from file open_manipulator_msgs/RelayRequest.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_RELAYREQUEST_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_RELAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_manipulator_msgs
{
template <class ContainerAllocator>
struct RelayRequest_
{
  typedef RelayRequest_<ContainerAllocator> Type;

  RelayRequest_()
    : Relay(false)  {
    }
  RelayRequest_(const ContainerAllocator& _alloc)
    : Relay(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Relay_type;
  _Relay_type Relay;





  typedef boost::shared_ptr< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelayRequest_

typedef ::open_manipulator_msgs::RelayRequest_<std::allocator<void> > RelayRequest;

typedef boost::shared_ptr< ::open_manipulator_msgs::RelayRequest > RelayRequestPtr;
typedef boost::shared_ptr< ::open_manipulator_msgs::RelayRequest const> RelayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Relay == rhs.Relay;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51f5c35c7d58c3899d91662099bc3872";
  }

  static const char* value(const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51f5c35c7d58c389ULL;
  static const uint64_t static_value2 = 0x9d91662099bc3872ULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_msgs/RelayRequest";
  }

  static const char* value(const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Relay\n"
;
  }

  static const char* value(const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Relay);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_msgs::RelayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_msgs::RelayRequest_<ContainerAllocator>& v)
  {
    s << indent << "Relay: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Relay);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_RELAYREQUEST_H
